"""Render docs/architecture-diagram.png from the Mermaid source.

This is a small one-shot helper (run from repo root):

    python docs/render_diagram.py

It draws a simple, readable architecture diagram with Pillow: two parallel
flows (SEC EDGAR batch + Finnhub streaming) converging on the FastAPI expose
layer, gated by APIM. Output is PNG at docs/architecture-diagram.png.

Kept dependency-light: Pillow + the Python stdlib only. Production-grade
diagrams would use Excalidraw / draw.io, but for a portfolio demo PNG
generated by this script is enough to ship the file the GitPlan lists.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


def _load_font(size: int) -> ImageFont.ImageFont:
    """Best-effort cross-platform font loader.

    Falls back to the PIL default bitmap font if no system TTF is found —
    the result is less polished but still legible.
    """
    candidates = [
        "C:/Windows/Fonts/segoeui.ttf",
        "C:/Windows/Fonts/arial.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/System/Library/Fonts/Helvetica.ttc",
    ]
    for path in candidates:
        try:
            return ImageFont.truetype(path, size=size)
        except OSError:
            continue
    return ImageFont.load_default()


# Color palette (kept minimal so the PNG reads well in README previews)
BG = (255, 255, 255)
BATCH_BG = (232, 244, 252)
STREAM_BG = (252, 240, 232)
EXPOSE_BG = (240, 252, 240)
NODE_FILL = (255, 255, 255)
NODE_BORDER = (60, 60, 60)
ARROW = (60, 60, 60)
TITLE = (20, 20, 20)
TEXT = (30, 30, 30)


def _wrap_text(text: str, font: ImageFont.ImageFont, max_width: int) -> list[str]:
    """Greedy word-wrap so labels fit inside their node boxes."""
    words = text.split()
    lines: list[str] = []
    current = ""
    for word in words:
        candidate = (current + " " + word).strip()
        bbox = font.getbbox(candidate)
        if bbox[2] - bbox[0] <= max_width:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def _draw_node(
    draw: ImageDraw.ImageDraw,
    label: str,
    x: int,
    y: int,
    width: int,
    height: int,
    font: ImageFont.ImageFont,
) -> tuple[int, int]:
    """Draw a rounded rectangle node with a multi-line centered label."""
    draw.rounded_rectangle(
        (x, y, x + width, y + height),
        radius=10,
        fill=NODE_FILL,
        outline=NODE_BORDER,
        width=2,
    )
    max_text_width = width - 16
    lines = _wrap_text(label, font, max_text_width)
    line_heights = [font.getbbox(line)[3] - font.getbbox(line)[1] for line in lines]
    total_height = sum(line_heights) + max(0, (len(lines) - 1) * 4)
    cx = x + width // 2
    cy = y + height // 2
    current_y = cy - total_height // 2
    for line, line_height in zip(lines, line_heights, strict=False):
        bbox = font.getbbox(line)
        text_width = bbox[2] - bbox[0]
        draw.text((cx - text_width // 2, current_y), line, fill=TEXT, font=font)
        current_y += line_height + 4
    return x + width // 2, y + height // 2


def _draw_arrow(
    draw: ImageDraw.ImageDraw,
    start: tuple[int, int],
    end: tuple[int, int],
    label: str | None = None,
    label_font: ImageFont.ImageFont | None = None,
) -> None:
    """Draw a horizontal arrow with an optional label centered above it."""
    draw.line([start, end], fill=ARROW, width=2)
    # Arrowhead
    if end[0] > start[0]:
        draw.polygon(
            [(end[0], end[1]), (end[0] - 10, end[1] - 5), (end[0] - 10, end[1] + 5)],
            fill=ARROW,
        )
    if label and label_font:
        mid_x = (start[0] + end[0]) // 2
        mid_y = (start[1] + end[1]) // 2 - 10
        bbox = label_font.getbbox(label)
        label_w = bbox[2] - bbox[0]
        draw.text((mid_x - label_w // 2, mid_y), label, fill=TEXT, font=label_font)


def _draw_subgroup(
    draw: ImageDraw.ImageDraw,
    title: str,
    bg_color: tuple[int, int, int],
    x0: int,
    y0: int,
    x1: int,
    y1: int,
    font: ImageFont.ImageFont,
) -> None:
    """Lightly tinted background + title for the batch/stream/expose groups."""
    draw.rounded_rectangle(
        (x0, y0, x1, y1),
        radius=14,
        fill=bg_color,
        outline=NODE_BORDER,
        width=1,
    )
    draw.text((x0 + 14, y0 + 8), title, fill=TITLE, font=font)


def render() -> Path:
    width, height = 1700, 900
    img = Image.new("RGB", (width, height), BG)
    draw = ImageDraw.Draw(img)
    title_font = _load_font(28)
    group_font = _load_font(20)
    node_font = _load_font(15)
    label_font = _load_font(13)

    draw.text((20, 12), "Azure Data Integration — Architecture", fill=TITLE, font=title_font)
    draw.text(
        (20, 50),
        "Two parallel flows (SEC EDGAR batch + Finnhub streaming) converge on FastAPI, gated by APIM.",
        fill=TEXT,
        font=label_font,
    )

    # ------------------------------------------------------------------ groups
    batch_box = (40, 100, 820, 520)
    stream_box = (40, 560, 820, 850)
    expose_box = (880, 100, 1660, 850)
    _draw_subgroup(draw, "SEC EDGAR batch flow (P0)", BATCH_BG, *batch_box, font=group_font)
    _draw_subgroup(draw, "Finnhub streaming flow (P1)", STREAM_BG, *stream_box, font=group_font)
    _draw_subgroup(draw, "Expose layer", EXPOSE_BG, *expose_box, font=group_font)

    # ------------------------------------------------------------ batch nodes
    batch_nodes = [
        ("SEC EDGAR\ncompanyfacts API", 80, 150),
        ("sec_edgar_adapter.py\n(flatten + fallback tags)", 270, 150),
        ("Blob Storage\nraw-sec", 470, 150),
        ("ADF Copy Activity\n(Blob → SQL)", 670, 150),
    ]
    batch_centers: list[tuple[int, int]] = []
    for label, nx, ny in batch_nodes:
        cx, cy = _draw_node(draw, label, nx, ny, 170, 90, node_font)
        batch_centers.append((cx, cy))

    staging = _draw_node(draw, "SQL: staging", 470, 290, 170, 60, node_font)
    transformed = _draw_node(
        draw, "SQL: company_revenue_yearly", 470, 430, 240, 70, node_font
    )
    databricks = _draw_node(
        draw, "Databricks\ntransform_revenue.py\n(dedupe + YoY)", 270, 380, 170, 120, node_font
    )

    # ------------------------------------------------------------ stream nodes
    stream_nodes = [
        ("Finnhub WebSocket\nwss://ws.finnhub.io", 80, 600),
        ("finnhub_ws_publisher\n(Container App)", 270, 600),
        ("Service Bus queue\nmarket-ticks", 470, 600),
        ("Azure Function\nQueue Trigger", 670, 600),
    ]
    stream_centers: list[tuple[int, int]] = []
    for label, nx, ny in stream_nodes:
        cx, cy = _draw_node(draw, label, nx, ny, 170, 90, node_font)
        stream_centers.append((cx, cy))
    live_ticks = _draw_node(draw, "SQL: live_ticks", 470, 740, 170, 60, node_font)

    # ------------------------------------------------------------ expose nodes
    api_node = _draw_node(
        draw,
        "FastAPI App Service\n/revenue/yearly\n/market/live",
        940,
        280,
        280,
        140,
        node_font,
    )
    apim_node = _draw_node(
        draw,
        "APIM gateway\n(subscription key\n+ rate limit)",
        1320,
        280,
        280,
        140,
        node_font,
    )

    # ------------------------------------------------------------- batch arrows
    for (start, end) in zip(batch_centers, batch_centers[1:], strict=False):
        _draw_arrow(draw, (start[0] + 85, start[1]), (end[0] - 85, end[1]))
    _draw_arrow(draw, (batch_centers[3][0], batch_centers[3][1] + 45), (staging[0], staging[1] - 30))
    _draw_arrow(draw, (staging[0], staging[1] + 30), (transformed[0], transformed[1] - 35))
    _draw_arrow(draw, (transformed[0] - 120, transformed[1]), (databricks[0] + 85, databricks[1]))
    _draw_arrow(draw, (databricks[0] - 85, databricks[1]), (staging[0] + 85, staging[1] + 10))

    # ------------------------------------------------------------ stream arrows
    for (start, end) in zip(stream_centers, stream_centers[1:], strict=False):
        _draw_arrow(draw, (start[0] + 85, start[1]), (end[0] - 85, end[1]))
    _draw_arrow(draw, (stream_centers[3][0], stream_centers[3][1] + 45), (live_ticks[0], live_ticks[1] - 30))

    # ------------------------------------------------------- converge into API
    _draw_arrow(draw, (transformed[0] + 120, transformed[1] - 10), (api_node[0] - 140, api_node[1] - 30))
    _draw_arrow(draw, (live_ticks[0] + 85, live_ticks[1] - 10), (api_node[0] - 140, api_node[1] + 30))
    _draw_arrow(draw, (api_node[0] + 140, api_node[1]), (apim_node[0] - 140, apim_node[1]))

    # ------------------------------------------------------- legend / footer
    legend_y = height - 40
    draw.text(
        (20, legend_y),
        "Rendered from docs/architecture-diagram.mmd via docs/render_diagram.py",
        fill=TEXT,
        font=label_font,
    )

    out = Path(__file__).parent / "architecture-diagram.png"
    img.save(out, format="PNG")
    return out


if __name__ == "__main__":
    path = render()
    print(f"Wrote {path}")
